server:
  port: 8000
spring:
  application:
    name: oauth2-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2-token?allowPublicKeyRetrieval=true&useSSL=false&amp&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
##Login Configuration
login:
  maxLoginAttempt: 5
  loginAttempPeriod: 1
  lockTimeAfterLoginFail: 2
