spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
producer:
  rabbitmq:
    exchange: marklove.exchange.logs
consumer:
  rabbitmq:
    queue1: sys.dev.info
    queue2: sys.test.error
    queue3: app.prod.error
