spring:
  application:
    name: upload-download-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
server:
  port: 9090
### Configuration bean storage ###
app:
  storage:
    bean: io.marklove.s3.uploaddowload.services.impl.S3StorageServiceImpl
### Configuration storage local ####
storage:
  dir:

