server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_database?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1
#    initialization-mode: never
#    platform: mysql
##JPA configuration##
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
##Liquibase configuration##
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
##Configuration Other##
check-user-scopes: true